name: Build and Pack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Pack NuGet package
      run: dotnet pack --no-build --configuration Release --output ./nupkg

    - name: Upload NuGet artifact
      uses: actions/upload-artifact@v4
      with:
        name: ComAutoWrapper-nupkg
        path: ./nupkg/*.nupkg